drone:
  behavior:
    ros__parameters:
      reached_thres: 0.3
      cruise_height: 5.0
      frequency: 10.0
      use_sim_time: true
  controller:
    ros__parameters:
      lookahead_distance: 1.0
      max_xy_vel: 0.4
      max_z_vel: 0.4
      yaw_vel: -0.3
      kp_xy: 1.2
      kp_z: 1.0
      kd_xy: 0.2
      kd_z: 0.2
      alpha_vel: 0.7
      frequency: 20.0
      enable: true
      use_sim_time: true
  planner:
    ros__parameters:
      interpolation_distance: 0.1
  estimator:
    ros__parameters:
      frequency: 30.0
      var_imu_x: 0.0007540079788071984
      var_imu_y: 0.0007540079788071984
      var_imu_z: 0.0026709504709959185
      var_imu_a: 4.335240730950364e-06
      var_gps_x: 4.991577107264711e-06
      var_gps_y: 4.991577107264711e-06
      var_gps_z: 2.6131922572951685e-06
      var_baro: 0.15808480957286788
      var_sonar: 0.001015863723890635
      var_magnet: 0.0001040617243299632
      use_sim_time: true
      use_ground_truth: false
      verbose: true
turtle:
  behavior:
    ros__parameters:
      waypoints:
      - 1.0
      - 4.0
      - -4.5
      - -2.0
      frequency: 1.0
      reached_thres: 0.05
      use_sim_time: true
  planner:
    ros__parameters:
      max_access_cost: 90
      use_sim_time: true
  controller:
    ros__parameters:
      frequency: 10.0
      kp_lin: 0.8
      kp_ang: 1.0
      max_lin_vel: 0.22
      max_ang_vel: 1.0
      xy_tolerance: 0.05
      yaw_tolerance: 0.78
      lookahead_distance: 0.3
      enable: true
      use_sim_time: true
  map_loader:
    ros__parameters:
      frame_id: /map
      max_cost: 99
      min_cost: 0
      topic_map: map
      topic_global_costmap: global_costmap
      circumscribed_radius: 0.2
      inflation_radius: 0.8
      cost_exponent: 8.0
